### ISSUE TITLE
flextable tests

### ISSUE THREAD

**Issue by davidgohel** [montesmariana/glossr#1]
Hello

I want to change some of HTML codes for flextable but will face issues when I will submit the new version because reverse deps check fails with glossr. 

Could you remove the tests you are doing on flextable outputs? For example, here I added an empty style and it makes your package fail on check.

If there is something important for you, we can include it in the tests of flextable, that way I am still able to change internals. 

```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test-gloss_render.R:75:3): gloss label renders in word ─────────────
  word\[\[2\]\] does not match "^```\\{=html\\}\\n<div class=\\\"tabwid tabwid_left\\\"><style>".
  Actual value: "\\n\\n``````\{=html\}\\n<style></style><div class="tabwid tabwid_left"><style>..."
  Backtrace:
      ▆
   1. └─testthat::expect_match(word[[2]], "^```\\{=html\\}\\n<div class=\\\"tabwid tabwid_left\\\"><style>") at test-gloss_render.R:75:2
   2.   └─testthat:::expect_match_(...)
```

KR
David

**Comment by montesmariana** [comment]
Hi! Sure! I think this test has to do with verbatim html in the rmarkdown, so I can remove it and check the output after your update. The main goal in glossr is to be able to make an invisible table in MS Word output, will I need to change any code?

However, I will not be able to do this before September 12th. After that I can take care of it.

Kind regards,
Mariana

**Comment by davidgohel** [comment]
No, you won't have to change any code, if you do, let me know.

I reversed the change I made, I will put it back in next version :)

**Comment by davidgohel** [comment]
hello,

Sorry for that, I have to submit a new version to CRAN tomorrow. 

I am facing another issue with the tests. I thought that the implemented tests did not let me add class names in the `class` attribute of the tag `<table>` in the HTML (because I have to check reverse dependencies). https://github.com/davidgohel/flextable/commit/073201968e4a8d7b11389d5986ad54f58c2c943a. 
I changed the code to get rid of this problem, but it still fails. 

* there (I am not sure if it is related to flextable): 

```
expect_snapshot_output(knit_print(
    as_gloss(a, b, translation = t, source = s, label = l,
             output_format = "leipzig")
  ))
```

* there:

```
expect_snapshot_output(knit_print(
    as_gloss(a, b, translation = t, source = s, label = l,
             output_format = "word")
  ))
```

It does not test any word but some HTML from flextable:

<img width="947" src="https://user-images.githubusercontent.com/4331618/190859284-d48a0bc6-f9c3-4144-b2a8-4fd4160ea91b.png" style="border:1px solid red;">

The issue is there because CSS names are randomly generated and because I cleaned and reorganized some code. 

<img width="750" alt="Capture d’écran 2022-09-17 à 15 01 09" src="https://user-images.githubusercontent.com/4331618/190858557-c8d9593e-09b9-41d0-9be7-eaa5e8756937.png">

It would be really nice if you could remove these tests, as this prevents automatic validation for updates on CRAN. I still need to work on flextable and testing the content that is generated make improvements and debugging difficult. Again, if there is something important for you, we can include it in the tests of flextable.

**Comment by montesmariana** [comment]
Hello,

No problem, I will remove the tests, but it is impossible for me until Monday, I am really sorry. I understand that you can report that in the cran_comments (that I was notified and what I responded). Monday I will remove the test and submit to CRAN as soon as I can.

**Comment by davidgohel** [comment]
thank you and sorry for the hassle!

**Comment by montesmariana** [comment]
I've just submitted a new version without the tests, now it's on CRAN's hands :)
As I said, my main interest is to be able to create a table with transparent lines in Word output. If you have tips on how to test that _that_ is rendering properly, I would love to hear them.
Thank you for your package ^^

**Comment by davidgohel** [comment]
Thank you,

> If you have tips on how to test that that is rendering properly, I would love to hear them.

I coded visual tests recently, an example can be found here:

https://github.com/davidgohel/flextable/blob/master/tests/testthat/test-borders.R#L56

expected result : 

https://github.com/davidgohel/flextable/blob/master/tests/testthat/_snaps/borders/docx-borders.png

It can not work on CRAN for Word and PowerPoint as it relies on Word and PowerPoint (using doconv). I think it should not be run on CRAN. I don't think it's possible, I use them only locally, but it's already a big advance.
