### ISSUE TITLE
glossr and flextable

### ISSUE THREAD

**Issue by davidgohel** [montesmariana/glossr#10]
hello,

`flextable_to_rmd()` is being refactored (see https://github.com/davidgohel/flextable/issues/614) to adapt to posit recommendation.

I've tested reverse dependencies and there is an issue with 'glossr'. I am not able to understand why this happens with your package. 

```
── Error (test-gloss_render.R:76:3): gloss label renders in word ───────────────
<purrr_error_indexed/rlang_error/error/condition>
Error in `purrr::map(gloss_lines, function(g) {
    g <- if (inherits(g, "flextable")) 
        g
    else gloss_table(g)
    flextable::flextable_to_rmd(g, ft.align = "left", print = FALSE)
})`: i In index: 1.
Caused by error in `setwd()`:
! character argument expected
```

Could you take a look and try to help me? I didn't think I broke something while using `knitr::knit_child` as recommended, but it appears I did... I am clueless on how I should inspect what is going on. `setwd()` is probably called by "knitr" and the manual tests I did with glossr_how.Rmd were OK. I suspect the issue to only happen in the tests.

It seems you are using raw output instead of relying on knitr print method, is it possible to only modify the Word output so that `officer::block_list` is used and the output mechanism is managed only by knitr instead of *output asis*? That way, `format_word_source()` and `flextable_to_rmd()` would not have to be called. Note I am not sure if this is the root cause.

KR
David

**Comment by montesmariana** [comment]
Hi David,

I am working on a new version of glossr that does not depend on flextable anymore :)
When printing the tables I had to do it inside of a numbered example, so relying on knitr was not working as I needed it to. But I'm taking a different path altogether now. I need to run some more tests before releasing the next version, but you may dismiss any incompatibilities with glossr because it won't have flextable as dependency from the next release.

Best,

Mariana

**Comment by davidgohel** [comment]
OK, thanks for your answer !

**Comment by davidgohel** [comment]
I understand better what your package does now and I think you just need standard markdown, pandoc/usual markdown can manage all your needs :)

**Comment by montesmariana** [comment]
Well, I couldn't figure out how to create an _invisible_ table for Word output, that's why I tried to use your package. Or do you know a way of telling pandog/usual markdown to align words vertically to each other?

**Comment by davidgohel** [comment]
Sorry, I did not catch that point. No I don't know, sorry. I think Pandoc only enable regular unformatted tables (I mean no color, no cell merging, etc.).

**Comment by montesmariana** [comment]
It's ok, no worries :) Thank you
