### ISSUE TITLE
flextable tests

### ISSUE THREAD

**Issue by davidgohel** [montesmariana/glossr#6]
Hello

In the tests of the package, this test is still causing issues for flextable (see also #1):
 
https://github.com/montesmariana/glossr/blob/main/tests/testthat/test-gloss_render.R#L77

I am not sure what does it test, it expects some HTML but is referenced as "gloss label renders in word". Also it is not executed from in a knitr context, so it's unlikely to understand what format is expected. 

Could you remove this test and not test the outputs of flextable. These are codes that can evolve, if you freeze them in your unit codes, we can't make the package evolve because the reversed dependencies prevent us from doing so.

**Comment by montesmariana** [comment]
Hi! Sorry I only now saw the message! I will remove the tests.

**Comment by davidgohel** [comment]
Thanks, 

you can maybe reuse https://github.com/davidgohel/flextable/blob/86365104f05cfa2ee756f02125b3a224784ee8e6/tests/testthat/test-borders.R#L58 to visual tests your word result (not advised for cran test but from experience it works very well locally and that's enough for me to detect regressions)

**Comment by davidgohel** [comment]
Hello, when do you plan to submit your new version? I may need to submit soon to avoid an issue with a small change in knitr (dev version for now).

**Comment by davidgohel** [comment]
Just to let you know, I don't need to submit very soon finally
