### ISSUE TITLE
docx output not rendering correctly

### ISSUE THREAD

**Issue by margisk** [montesmariana/glossr#7]
Hello, I have encountered an issue with the docx output being rendered incorrectly, basically I get what looks like a long XML dump, but not a table.

I am using R 4.3.0, glossr 0.7.0, flextable 0.9.1, officedown 0.3.0. Knitting to HTML works fine. I have tested this on my Linux system and on Windows (freshly installed R and all packages in the latter case), both in Libreoffice Writer/Microsoft Word, it's the same.

Here is the code I am trying to run (from the vignette example)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glossr)
```

```{r, using_glossr, include=FALSE}
use_glossr()
```

```{r, first-gloss}
my_gloss <- as_gloss(
  "她 哇的一聲 大 哭起來，",
  "tā wā=de-yì-shēng dà kū-qǐlái,",
  "TSG waa.IDEO-LINK-one-sound big cry-inch",
  translation = "Waaaaa, she began to wail.",
  label = "my-label",
  source = "ASBC (nº 100622)"
)
my_gloss
```

I get something like [this](https://imgur.com/a/TkGp1O6) (only a few lines included, the actual output is several pages long. Only the "source" field is rendered correctly in the output.

I suspect it has something to do with officedown or flextable, but I am not sure what it might be. Could you let me know if you can replicate the issue? Thanks in advance.

**Comment by montesmariana** [comment]
Hello! Thank you for reporting the issue! That does not look good indeed.
Could you tell me if you are knitting from an Rmd file or a qmd file (and in that case which version of rmarkdown / Quarto)?
I will try to replicate it later toda.

**Comment by margisk** [comment]
I am knitting from Rmd, rmarkdown version 2.21

**Comment by montesmariana** [comment]
Hi again!
I did manage to reproduce the issue (and in fact with Quarto there is also a problem with Word output, albeit differently).
The source of the problem is most likely changes in the latest versions of `{flextable}`, the package being used to generate invisible tables in Word. I'm afraid I need to do some research to figure out whether I can circunvent the changes or whether I should try another package to generate the tables :(
This will take some time.
Thank you so much for reporting this (and for using glossr!) and I'm sorry for the inconvenience >.<

**Comment by kc-li** [comment]
Hi I've been encountering the same issue so I'll add my vote here. I'm also trying to knit from a Rmd to a word document. Initially I though it might be me using Chinese characters and IPA symbols, but then I found out as long as there are more than two lines to align (even all simple English), similar errors occur

I'll work with the HTML format for now, which seems fine! I hope knitting to word_document can be fixed as this can be really useful! Many thanks!

**Comment by montesmariana** [comment]
Hi!
One thing you can do to already have a nicer output is to add `results='asis'` to the chunk where you render your gloss. You can also add `ft.align='left'` so the tables are aligned to the left. This takes care of part of the problem but not the whole thing (if you have a 'source', it will be printed after the table...).

I'm working on properly fixing the output, but it's not as straightforward as it used to be. Thank you for your patience and for using glossr!

**Comment by AntheSevenants** [comment]
Coming along to add that I also experience this issue ☹️. This is probably superfluous, but:
- Quarto 1.1.189 from VS Code
- WSL 2 inside Windows 11

I'm happy to help if I know where to look in the source 🫣.

**Comment by montesmariana** [comment]
Hi! I'm back!
I am working on this issue: glossr won't use flextable anymore but instead compute the width of the words and pad with spaces. If any of you would like to test this out before I release it and give me feedback let me know!

**Comment by AntheSevenants** [comment]
I'd be glad! 🙂

**Comment by montesmariana** [comment]
Lovely! :) You can install and try out the development version with:

```r
devtools::install_github("montesmariana/glossr@dev")
```

For now the rendering seems quite OK in the vignettes _except_ when Chinese characters are used.

Note: there are also other updates in how things get configured, check the styling vignette ;)

**Comment by montesmariana** [comment]
The solution is not perfect but at least it looks better than when flextable just wasn't working in glossr anymore.
Solved in 3433ee2ac449bd8011971bd5ec926e5b25bb09fe then!

**Comment by AntheSevenants** [comment]
Hi Mariana, sorry -- I completely forgot about this! I can confirm output is fixed in my document! Many many thanks!

**Comment by montesmariana** [comment]
Good because now that is what the current version in CRAN does :)
